// Midterm 3 Questions Array
const midterm3Questions = [
    {
        question: "When marketers use online commercial databases and internet search engines to collect data, what type of data are they collecting?",
        options: [
            "Primary data",
            "Secondary data",
            "Big data",
            "Ethnographic data",
            "Internal data"
        ],
        correct: "Secondary data"
    },
    {
        question: "Shine Enterprises mass produces an all-purpose floor cleaner that is aimed at the whole market. This firm uses a(n) ________ marketing strategy.",
        options: [
            "Individual",
            "Niche",
            "Undifferentiated",
            "One-to-one",
            "Segmented"
        ],
        correct: "Undifferentiated"
    },
    {
        question: "Gilron Holidays runs a premium membership club that caters to customers whose annual salary exceeds $100,000. Members of this club are offered seasonal discounts on select luxury hotels in select cities worldwide. Gilron Holidays most likely follows a(n) ________ segmentation approach.",
        options: [
            "Income",
            "Geographic",
            "Gender",
            "Occasion",
            "Benefit"
        ],
        correct: "Income"
    },
    {
        question: "________ is the first step in the marketing research process.",
        options: [
            "Analyzing data",
            "Defining the problem and research objectives",
            "Collecting data",
            "Developing the research plan",
            "Interpreting and reporting the findings"
        ],
        correct: "Defining the problem and research objectives"
    },
    {
        question: "BMW says their cars are \"The Fastest Driving Machine.\" Ford trucks are \"Built to Last.\" Which type of differentiation do these examples represent?",
        options: [
            "Image differentiation",
            "People differentiation",
            "Services differentiation",
            "Channel differentiation",
            "Product differentiation"
        ],
        correct: "Product differentiation"
    },
    {
        question: "Huge and complex data sets generated by today's sophisticated information generation, collection, storage, and analysis technologies are referred to as ________.",
        options: [
            "Marketing research",
            "Customer insights",
            "Competitive marketing intelligence",
            "A marketing information system",
            "Big data"
        ],
        correct: "Big data"
    },
    {
        question: "Marketers who use ________ often segment their markets by consumer lifestyles and base their marketing strategies on lifestyle appeals.",
        options: [
            "Demographic segmentation",
            "Benefit segmentation",
            "Psychographic segmentation",
            "Occasion segmentation",
            "Geographic segmentation"
        ],
        correct: "Psychographic segmentation"
    },
    {
        question: "Ferrari sports cars claim superior quality, performance, and style. Ferrari provides \"perfection\" at a premium price to keep its brand image intact. Which type of value proposition does Ferrari most likely position its products with?",
        options: [
            "More for the same",
            "Less for much less",
            "More for more",
            "The same for less",
            "More for less"
        ],
        correct: "More for more"
    },
    {
        question: "An American cola-manufacturing company that primarily targets rebellious and adventurous people most likely uses ________ segmentation.",
        options: [
            "Benefit",
            "Psychographic",
            "Occasion",
            "Income",
            "Geographic"
        ],
        correct: "Psychographic"
    },
    {
        question: "When researchers select the easiest population members from which to collect information, they are using a ________ sample.",
        options: [
            "Simple random",
            "Convenience",
            "Cluster",
            "Stratified random",
            "Quota"
        ],
        correct: "Convenience"
    }
];

const midterm3Explanations = [
    {
        explanation: "Secondary data is information already collected and available (not gathered firsthand).",
        example: "A company using Google searches or industry reports to analyze competitors."
    },
    {
        explanation: "An undifferentiated strategy targets the whole market with one offer, ignoring differences.",
        example: "Selling one floor cleaner brand to everyone without customizing for different customer groups."
    },
    {
        explanation: "Income segmentation divides the market based on income levels.",
        example: "Offering luxury hotel discounts to people earning over $100,000 annually."
    },
    {
        explanation: "Research starts by defining the problem clearly to guide data collection.",
        example: "A company wants to know why sales dropped, so they first set that as their research goal."
    },
    {
        explanation: "Product differentiation focuses on unique product features or performance.",
        example: "BMW highlighting speed; Ford emphasizing durability."
    },
    {
        explanation: "Big data refers to extremely large data sets processed to find patterns and trends.",
        example: "Amazon analyzing millions of customer purchases to recommend products."
    },
    {
        explanation: "Psychographic segmentation divides the market based on lifestyles, interests, or personality.",
        example: "Targeting eco-conscious consumers with sustainable products."
    },
    {
        explanation: "More for more offers higher quality or luxury at a premium price.",
        example: "Ferrari cars cost more but promise top quality, style, and performance."
    },
    {
        explanation: "This company uses psychographic segmentation, focusing on customers' attitudes and personality.",
        example: "Advertising cola as the choice for adventurous, non-conforming people."
    },
    {
        explanation: "A convenience sample involves choosing the easiest, most accessible people for research.",
        example: "Surveying students at a nearby campus because they're easy to reach."
    }
];

let midterm3Submissions = [];

function showMidterm3Test() {
    const content = document.getElementById('course-content');
    content.innerHTML = `
        <div class="quiz-wrapper">
            <h2>Midterm 3</h2>
            <div id="quiz-container">
                ${midterm3Questions.map((q, index) => `
                    <div class="quiz-question">
                        <p><strong>Question ${index + 1}:</strong> ${q.question}</p>
                        <div class="options" style="display: flex; flex-direction: column; gap: 10px;">
                            ${q.options.map(option => `
                                <button class="option-btn" style="width: 100%; text-align: left; padding: 10px;" onclick="selectMidterm3Option(this, ${index})">${option}</button>
                            `).join('')}
                        </div>
                    </div>
                `).join('')}
                <div class="nav-container">
                    <button class="nav-btn" onclick="checkAndSubmitMidterm3()">Submit Test</button>
                    <button class="nav-btn secondary" onclick="showMainMenu()">Back to Menu</button>
                </div>
            </div>
        </div>
    `;
}

function selectMidterm3Option(button, questionIndex) {
    // Get all option buttons for this question
    const questionDiv = button.closest('.quiz-question');
    const allOptions = questionDiv.querySelectorAll('.option-btn');
    
    // Remove selected class from all options in this question
    allOptions.forEach(btn => btn.classList.remove('selected'));
    
    // Add selected class to clicked button
    button.classList.add('selected');
}

function checkAndSubmitMidterm3() {
    const questions = document.querySelectorAll('.quiz-question');
    const unansweredCount = Array.from(questions).filter(q => !q.querySelector('.option-btn.selected')).length;
    
    if (unansweredCount > 0) {
        const confirmSubmit = confirm(`Warning: You have ${unansweredCount} unanswered question${unansweredCount > 1 ? 's' : ''}. Do you want to submit anyway?`);
        if (!confirmSubmit) {
            return;
        }
    }
    
    submitMidterm3();
}

function submitMidterm3() {
    // Create an array of all questions with their selected answers
    const questions = document.querySelectorAll('.quiz-question');
    let score = 0;
    const answers = [];
    
    // Go through each question
    questions.forEach((questionDiv, index) => {
        const selectedButton = questionDiv.querySelector('.option-btn.selected');
        const answer = {
            question: midterm3Questions[index].question,
            answer: selectedButton ? selectedButton.textContent : 'Not answered',
            correct: midterm3Questions[index].correct,
            isCorrect: false
        };
        
        // Check if the question was answered and if it's correct
        if (selectedButton) {
            answer.isCorrect = selectedButton.textContent === midterm3Questions[index].correct;
            if (answer.isCorrect) score++;
        }
        
        answers.push(answer);
    });

    // Store the submission
    const submission = {
        date: new Date().toLocaleString(),
        score: score,
        total: midterm3Questions.length,
        answers: answers,
        unansweredCount: answers.filter(a => a.answer === 'Not answered').length
    };

    if (!midterm3Submissions) {
        midterm3Submissions = [];
    }
    midterm3Submissions.unshift(submission);

    showMidterm3Review(0);
}

function showMidterm3Review(submissionIndex) {
    const submission = midterm3Submissions[submissionIndex];
    const content = document.getElementById('course-content');
    
    content.innerHTML = `
        <div class="quiz-wrapper">
            <h2>Midterm 3 Review</h2>
            <div class="review-progress">
                <span>Score:</span>
                <div class="progress-bar">
                    <div class="progress-fill" style="--progress: ${(submission.score / submission.total) * 100}%"></div>
                </div>
                <span>${submission.score}/${submission.total}</span>
            </div>
            <div class="submissions-list">
                ${submission.answers.map((answer, index) => `
                    <div class="review-card ${answer.isCorrect ? 'correct' : 'incorrect'}">
                        <p><strong>Question ${index + 1}:</strong> ${answer.question}</p>
                        <p>Your answer: ${answer.answer}</p>
                        <p>Correct answer: ${answer.correct}</p>
                        ${index < midterm3Explanations.length ? `
                            <div class="flyout-menu">
                                <button class="flyout-button">View Explanation</button>
                                <div class="flyout-content">
                                    <div class="explanation-title">Explanation:</div>
                                    <div class="explanation-text">
                                        ${midterm3Explanations[index].explanation}
                                    </div>
                                    <div class="example-title">Example:</div>
                                    <div class="example-text">
                                        ${midterm3Explanations[index].example}
                                    </div>
                                </div>
                            </div>
                        ` : ''}
                    </div>
                `).join('')}
            </div>
            <div class="nav-container">
                <button class="nav-btn" onclick="showMidterm3Submissions()">Back to Submissions</button>
                <button class="nav-btn secondary" onclick="showMainMenu()">Back to Menu</button>
            </div>
        </div>
    `;
}

function showMidterm3Submissions() {
    const content = document.getElementById('course-content');
    const submissions = midterm3Submissions || [];
    
    content.innerHTML = `
        <div class="quiz-wrapper">
            <h2>Midterm 3 Submissions</h2>
            ${submissions.length === 0 ? 
                '<p>No submissions yet.</p>' :
                submissions.map((sub, index) => {
                    const progress = (sub.score / sub.total) * 100;
                    return `
                        <div class="review-card">
                            <div class="review-progress">
                                <span>${sub.score}/${sub.total}</span>
                                <div class="progress-bar">
                                    <div class="progress-fill" style="width: ${progress}%"></div>
                                </div>
                                <span>${Math.round(progress)}%</span>
                            </div>
                            <p>${sub.date}</p>
                            <button class="quiz-btn" onclick="showMidterm3Review(${index})">Review Answers</button>
                        </div>
                    `;
                }).join('')
            }
            <div class="nav-container">
                <button class="nav-btn" onclick="showMainMenu()">Back to Menu</button>
            </div>
        </div>
    `;
}
